In [1]:
import numpy as np
import pandas as pd
from modules.KNNClassifier import KNNClassifier
from sklearn import neighbors, model_selection, preprocessing, metrics

In [2]:
# Загрузка данных
wine_df = pd.read_csv("../../data/wine_preprocessed.csv")
wine_df = wine_df.drop(columns="Unnamed: 0")
wine_df.head()

Cultivar  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0         1    14.23        1.71  2.43               15.6        127   
1         1    13.20        1.78  2.14               11.2        100   
2         1    13.16        2.36  2.67               18.6        101   
3         1    14.37        1.95  2.50               16.8        113   
4         1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315  Proline  
0             5.64  1.04         3.92     1065  
1             4.38  1.05         3.40     1050  
2             5.68  1.03         3.17     1185  
3             7.80  0.86         3.45     1480  
4             4.32  1.04         2.93      735

In [3]:
# Отделение ключевого атрибута
X = wine_df.drop(columns='Cultivar').values
y = wine_df.iloc[:, :1].values
y = y.ravel()

In [4]:
# Разделение выборки на обучение и тест

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y)

In [5]:
# Масштабирование выборки
scaler = preprocessing.StandardScaler()

X_train = scaler.fit_transform(X_train, y_train)
X_test = scaler.transform(X_test)

In [6]:
# инициализация моделей
sklearn_knn = neighbors.KNeighborsClassifier(weights='distance', p=3)
knn = KNNClassifier(metric='minkowski')

In [7]:
%%time

# Обучение моделей
sklearn_knn.fit(X_train, y_train)

Wall time: 1 ms


KNeighborsClassifier(p=3, weights='distance')

In [8]:
%%time

knn.fit(X_train, y_train)

Wall time: 1.01 ms


In [9]:
%%time

# Получение результатов
sklearn_y_pred = sklearn_knn.predict(X_test)

Wall time: 3 ms


In [10]:
%%time

y_pred = knn.predict(X_test)

Wall time: 83 ms


In [11]:
# Сравнение результатов работы
print("SKLEARN KNN: ")
print(metrics.confusion_matrix(y_test, sklearn_y_pred))
print(metrics.classification_report(y_test, sklearn_y_pred))

print('KNN: ')
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))


SKLEARN KNN: 
[[16  0  0]
 [ 1 17  1]
 [ 0  0 10]]
              precision    recall  f1-score   support

           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94        19
           3       0.91      1.00      0.95        10

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

KNN: 
[[16  0  0]
 [ 1 17  1]
 [ 0  0 10]]
              precision    recall  f1-score   support

           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94        19
           3       0.91      1.00      0.95        10

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



### Вывод
Можно сказать, что реализованная модель отработала на одном уровне с моделью из sklearn.<br>
Однако, несложно заметить, что время поиска ответов у реализованной модели намного больше, чем у модели из sklearn.